version: '3'

services:
  mon-nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Accès via http://IP-de-ton-Rocky:8080

  mon-portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443" # Accès via https://IP-de-ton-Rocky:9443
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock # Donne à Portainer l'accès à Podman
      - portainer_data:/data

volumes:
  portainer_data:
